apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-secrets
  namespace: ai-agents
type: Opaque
data:
  # Base64 encoded placeholder - will need to be replaced with actual encoded API key
  openai-api-key: UkVQTEFDRV9XSVRIX1lPVVJfQVBJX0tFWQ==
