apiVersion: v1
kind: Service
metadata:
  name: browser-use-agent
  namespace: ai-agents
spec:
  selector:
    app: browser-use-agent
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
